Repository evolution-cms/evolution, pull requests merged in 2018-10, with the labels that each got.

#831 Update model and processors for work with user and webuser
  core/src/Models/ManagerUser.php
  core/src/Models/MemberGroup.php
  core/src/Models/UserAttribute.php
  core/src/Models/UserSetting.php
  core/src/Models/WebGroup.php
  core/src/Models/WebUser.php
  core/src/Models/WebUserAttribute.php
  core/src/Models/WebUserSetting.php
  manager/processors/delete_user.processor.php
  manager/processors/delete_web_user.processor.php
  manager/processors/save_password.processor.php
  manager/processors/save_user.processor.php
  manager/processors/save_web_user.processor.php
Labels: Area/Core, Area/Manager, Priority/Normal, Status/Need-test, Type/Enhancement

#779 Change checking of manager mode
  assets/lib/class.modxRTEbridge.php
Labels: Area/Core, Priority/Normal, Type/Enhancement

#832 Update work with TV and small code style fix
  core/functions/processors.php
  core/src/Models/SiteContent.php
  core/src/Models/SiteTmplvar.php
  core/src/Models/SiteTmplvarAccess.php
  core/src/Models/SiteTmplvarContentvalue.php
  core/src/Models/SiteTmplvarTemplate.php
  manager/processors/delete_tmplvars.processor.php
  manager/processors/delete_user.processor.php
  manager/processors/delete_web_user.processor.php
  manager/processors/duplicate_tmplvars.processor.php
  manager/processors/save_password.processor.php
  manager/processors/save_tmplvars.processor.php
  manager/processors/save_user.processor.php
  manager/processors/save_web_user.processor.php
Labels: Area/Core, Area/Manager, Priority/Normal, Status/Need-test, Type/Enhancement

#835 Update processors snippets and chunk to work with models
  core/src/Support/DocBlock.php
  manager/processors/delete_htmlsnippet.processor.php
  manager/processors/delete_snippet.processor.php
  manager/processors/duplicate_htmlsnippet.processor.php
  manager/processors/duplicate_snippet.processor.php
  manager/processors/save_htmlsnippet.processor.php
  manager/processors/save_snippet.processor.php
Labels: Area/Manager, Type/Enhancement

#837 Fix JS error – typo
  assets/plugins/managermanager/widgets/mm_hidefields/mm_hidefields.php
Labels: Area/Packages, Type/Bug

#806 Update snippet.docinfo.php
  assets/snippets/docinfo/snippet.docinfo.php
Labels: Area/Packages, Priority/Low, Type/Enhancement

#844 [F] Event reference fix
  manager/includes/document.parser.class.inc.php
Labels: Area/Core

#850 fix ip lenght for work with ipw6 #849
  install/setup.sql
Labels: Area/Core, Type/Enhancement

#851 fix ip lenght for work with ipv6 #849
  install/stubs/sql/setup.sql
Labels: Area/Core, Type/Enhancement

#872 Rename "Создать PHP-файл" to "Создать файл"
  manager/includes/lang/english.inc.php
  manager/includes/lang/russian-UTF8.inc.php
Labels: Area/Lang, Lang/English, Lang/Russian, Type/Enhancement

#875 Polish translations
  install/lang/polish-utf8.inc.php
  manager/includes/lang/polish-utf8.inc.php
Labels: Area/Install, Area/Lang, Lang/Polish
